### ISSUE TITLE
paper #759

### ISSUE THREAD

**Issue by kstolee** [researchart/fse20#119]
This issue is for discussion related to PR #9 

Author contact: @Jacob-yen

**Comment by kstolee** [comment]
## Authors information:

| Name          | Email Address          | **Github id** |
| ------------- | ---------------------- | ------------- |
| Zan Wang      | wangzan@tju.edu.cn     | tjuwangzan    |
| Ming Yan      | yanming@tju.edu.cn     | jacob-yen     |
| Junjie Chen * | junjiechen@tju.edu.cn  | JunjieChen    |
| Shuang Liu    | shuang.liu@tju.edu.cn  | AbigailLiu    |
| Dongdi Zhang  | zhangdongdi@tju.edu.cn | Dandy-John    |

\* *corresponding author*

**Comment by art-reviewer** [comment]
[Paper](https://github.com/Jacob-yen/fse20/blob/cced21b62e05b9899daee45cd2bf3ede6a2cd936/submissions/reusable/MingYan_fse20main-paper759-p/esecfse2020-paper759.pdf)

**Comment by AEreviewer** [comment]
Hi @Jacob-yen, I see in the documentation of your artifact that I have to install nvidia-docker2. Does that mean that I need a NVIDIA graphical card or any other specific hardware to run your experiment?  

Also, I see that you indicate in `STATUS.md` that your artifact is available but I don't see any DOI. Has the whole artifact been uploaded to a dedicated data repository (like Zenodo)?

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi Authors,

Overall the documentation you provided goes into details in terms of installation, set-up the environment, and running the tool. I also appreciate the fact that a docker container is made available. However, there are several serious issues with the availability of the artifacts.

## Recommend Badges: None (Requires Available Artefacts)

### Available
The artifacts should be uploaded on an archival repository (such as Zenodo) and with a public DOI. Unfortunately, OneDrive does not satisfy this requirement.

### Functional
Even if I download the files from OneDrive, and extract them in the data folder of the docker container, I am not able to run the code. Specifically, there are no scripts to run neither in the docker container nor into the extracted zip files. In this stage, the authors suggest to clone the repository:

> Step 1: Clone the repository. 

But the current repository does not contain code, it only contains md files. So eventually there is nothing to run. I believe the authors may have uploaded their code on some other github repository which is not linked in the documentation.

```
(lemon) root@7a9b0b7352b1:~/redis-4.0.8/src# python -u -m run.mutation_executor demo.conf
/root/anaconda3/envs/lemon/bin/python: Error while finding module specification for 'run.mutation_executor' (ModuleNotFoundError: No module named 'run')
```

### Reusable
The quality of the documentation appears to be good, but given the fact that the previous requirements were not satified (Available and Functional), this badge cannot be issued.

**Comment by Jacob-yen** [comment]
To @AEreviewer ‘s comments:：

Thanks for reviewing our artifacts.
We are sorry that we misunderstood the instructions on the FSE webpage. That is, we mistakenly think that only applying for an available badge requires DOI but applying reusable badge does not. We list the DOI links of our artifact and dataset as following:
dataset: https://doi.org/10.5281/zenodo.3898482
artifact: https://doi.org/10.5281/zenodo.3898469

We conducted all our experiments on the GPU. In order to reproduce our experiments, we provided the docker image which needs to run on GPU. However, LEMON can run on the CPU when we specifically configure the environment for it (converting all libraries to CPU version). At the same time, running LEMON on the CPU will take more time than the GPU.
You can also visit LEMON's homepage from the link below：
https://github.com/Jacob-yen/LEMON

**Comment by Jacob-yen** [comment]
To @RandomlyGeneratedReviewerAccount  ‘s comments:

Thanks for reviewing our artifacts. I am sorry that we did not put the link of LEMON's repository in `README.md`. Instead, we released the link in `CONTACT.md` which may have caused you to not find our repository. You can also visit LEMON's homepage from the link below：
https://github.com/Jacob-yen/LEMON

The DOI links of our artifact and dataset are as following:
dataset: https://doi.org/10.5281/zenodo.3898482
artifact: https://doi.org/10.5281/zenodo.3898469

Please let me know if you have any questions about running LEMON.

**Comment by AEreviewer** [comment]
cc @Jacob-yen 

I have used the provided guidelines to check the different aspects of the artifact. Overall, it is good but it misses some documentation elements on the dataset used, and on the extension procedure to be qualified as reusable (see comment below).

- [x] Available: The artifact is placed on a publicly accessible archival repository and has a DOI.

- [ ] Functional: **I could not execute the scripts due to the specific hardware it requires. I trust @RandomlyGeneratedReviewerAccount review's regarding the execution of the artifact.**
  - [x] Documented: At minimum, an inventory of artifacts is included, and sufficient description provided to enable the artifacts to be exercised.

  - [ ] Consistent: The artifacts are relevant to the associated paper, and contribute in some inherent way to the generation of its main results.

  - [ ] Complete: To the extent possible, all components relevant to the paper in question are included. (Proprietary artifacts need not be included. If they are required to exercise the package then this should be documented, along with instructions on how to obtain them. Proxies for proprietary data should be included so as to demonstrate the analysis.)

  - [ ] Exercisable: Included scripts and/or software used to generate the results in the associated paper can be successfully executed, and included data can be accessed and appropriately manipulated.

- [ ] Reusable: Available + Functional + very carefully documented and well-structured to the extent that reuse and repurposing is facilitated.

Comments:

- The artifact itself is documented and explains how to run the different commands. However, since it requires specific hardware, I was not able to run it.

- The dataset uploaded to Zenodo (dataset: https://doi.org/10.5281/zenodo.3898482) does not contain any explanation about what is in the archive, making it hard to understand how it relates to the artifact: https://doi.org/10.5281/zenodo.3898469 used to replicate the evaluation. The dataset also contains only 3 files while the artifact readme file lists 12 datasets used for the evaluation.

- Results of the evaluation are not provided in the artifact. It is not possible to reproduce the analysis presented in the paper.

- The artifact briefly mentions how it can be extended by pointing at different files but does not provide any additional information. Some additional explanations would be nice to allow other researchers to use it properly and qualify the artifact as reusable.

**Comment by kstolee** [comment]
@RandomlyGeneratedReviewerAccount based on the updates, are you able to recommend the ```available``` badge?

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi Authors,

Thanks for reporting the DOI. Please, make sure to add it also within the documentation (and not only in this issue).

### Recommended Badge: Available

@kstolee and @Jacob-yen, I did give another try to run the code and replicate the results (in order to assign the Functional badge), after downloading the code.

Unfortunately, the process still fails, so I'm not able to run the code nor suggest the functional badge.
After the set up process, this is the error that I get:

```
(lemon) root@dab8ce2cb479:/data/Jacob-yen-LEMON-bf4680c# ls
LICENSE  README.md  config  esecfse2020-paper759.pdf  lemon_requirements.txt  run  scripts
(lemon) root@dab8ce2cb479:/data/Jacob-yen-LEMON-bf4680c# python -u -m run.mutation_executor demo.conf
Traceback (most recent call last):
  File "/root/anaconda3/envs/lemon/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/lemon/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/data/Jacob-yen-LEMON-bf4680c/run/mutation_executor.py", line 9, in <module>
    from scripts.tools import utils
  File "/data/Jacob-yen-LEMON-bf4680c/scripts/tools/utils.py", line 4, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

However, I do appreciate the efforts of the authors in creating a curated documentation. I encourage the authors to update this in the future, even if we consider this review finished.

**Comment by kstolee** [comment]
I'll tentatively apply the ```available``` badge. 

@Jacob-yen please cite the artifact from your paper and include the DOI in the references section.

**Comment by Jacob-yen** [comment]
Hi @kstolee @RandomlyGeneratedReviewerAccount ,
Thanks again for reviewing our artifact. After checking the provided error message, I noticed that it was caused by the missing installation of `pillow` (a python third-party library). However, in our provided `README.md`, we did list the installation step for this library. We believe that our artifact could run successfully if following our provided steps (including `Environment installation`, `Redis Startup`, and `Running LEMON` ) in `README.md`.

We sincerely hope to acquire an opportunity for running our artifact following our `README.md` steps.

Regarding the reported error message, more details about its installation is explained as follows:
In [README.md](https://github.com/Jacob-yen/LEMON/blob/master/README.md):
```
...
# default lemon python
conda create -n lemon python=3.6
source activate lemon
pip install -r lemon_requirements.txt
pip install keras==2.2.4
pip install tensorflow-gpu==1.14.0
source deactivate
```

`pip install -r lemon_requirements.txt` will automatically install the third-party libraries provided in `lemon_requirements.txt`. The content of `lemon_requirements.txt` is:

> pandas==0.23.0
> Pillow==5.1.0
> redis==3.3.2
> scikit-image==0.13.1
> scikit-learn==0.19.1
> scipy==1.1.0

`Pillow==5.1.0` is the library mentioned in the error message. This error should not occur after `Pillow` is installed correctly.

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi Authors,

Thanks for investigating the issue.
You are correct, the problem was related to those missing libraries.
Note that the documentation is currently not precise, and following it step-by-step leads to those missing dependencies. Let me explain. 

In Step 1 you suggest to clone the repository in the /your/local/path/ folder. 
In Step 2 we create the container where the /data/ folder points to /your/local/path/ and run it.

At this point, the container starts in the root folder (not in the data folder!).
You could either change the running docker command to go directly in the data folder, or remind the user to change folder before creating the conda environment.


### Recommended badge: Available & Reusable
The scripts run fine and the documentation is overall well curated.
The authors provide docker containers and steps to create the environments, which facilitate the reusability, given the complex task.

**Comment by kstolee** [comment]
Excellent news! Thanks for the reviews and discussion, @RandomlyGeneratedReviewerAccount and @AEreviewer .  

@Jacob-yen please cite your artifact using the DOI in the references section of your paper. I also suggest that you update your documentation and/or docker container as suggested by @RandomlyGeneratedReviewerAccount  to make it easier for future users of your artifact.

**Comment by Jacob-yen** [comment]
Hi @kstolee @AEreviewer @RandomlyGeneratedReviewerAccount 
Thanks so much for your efforts and constructive suggestions about our artifact! I will further refine our documents and docker container according to the suggestions as soon as possible :-)
