### ISSUE TITLE
Paper #260: Do the machine learning models on a crowd sourced platform exhibit bias?

### ISSUE THREAD

**Issue by kstolee** [researchart/fse20#80]
This issue is for discussion related to PR #46 

Authors are applying for the *reusable*, *functional*, and *available* badges.

Author contact: @sumonbis

**Comment by kstolee** [comment]
# Authors
Sumon Biswas (sumon@iastate.edu) and Hridesh Rajan (hridesh@iastate.edu), Iowa State University.

**Comment by art-reviewer** [comment]
[Paper](https://github.com/sumonbis/fse20/blob/431a8a50b8dc7c8aec5ca1d834adedf1a0237bdc/submissions/reusable/fse20main-p260-p/ml-fairness.pdf)

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi Authors,

Thanks for submitting and contributing to open science.
Overall, the documentation appears to be well curated, however there are some issues that do not allow me to replicate the results.

### Recommended Badge: Available

#### Available
The authors uploaded the artifacts on an archival system with DOI.

#### Functional
Overall, the documentation appears to be nice and complete, however there are issues with paths which made the scripts not functional and cannot reproduce the results. Note that I downloaded and worked from the unzipped Zenodo file.

There are several mistakes in the documentation:

> Navigate to the source code directory of cloned ML-Fairness repository ML-Fairness/src/ using the command line environment (mlfairness) $ from setup step 2.
> 
> Under each of the 5 tasks (german, adult, bank, home, titanic), there are separate python scripts to compute fairness.

This is incorrect. The 5 task folders are in ML-Fairness/src/models/

The following command fails:
```
(mlfairness) root@4b7367b3bcc8:/data/sumonbis-ML-Fairness-a721270/src/models# ./models.sh titanic 1
Started running model 1 for the task titanic
Traceback (most recent call last):
  File "titanic/model1.py", line 6, in <module>
    from utils.packages import *
ModuleNotFoundError: No module named 'utils.packages'
```

This is probably due to mistakes in the script with:
`sys.path.append('../')`
I gave my best effort in copying the folder utils in different locations (and within the model's folder) but without success.

Other inaccuracies in the documentation:

> Navigate to ML-Fairness/src/ and run python titanic-all.py. This will show success message on the command line.

There is no such python file titanic-all.py.
I did try to run a single model (e.g., model2.py) but without success, given the errors with the import.


Finally, the installation of the AIF360 package (which may not be needed for the titanic project, since it is not mentioned in the documentation), fails on this:

`ERROR: Failed building wheel for scs`


#### Reusable
Cannot qualify, given it is not functional.

**Comment by sumonbis** [comment]
Hi @RandomlyGeneratedReviewerAccount,

Thanks for your review. I have fixed the issues and updated the documentation. I have tested it on Mac OS. Let me know if it works. Otherwise, I can provide Anaconda environment file (.yml) where the packages are already installed. Here are the responses: 

Yes, you are correct. The correct path should be `ML-Fairness/src/models/ `. I have updated this in the INSTALL.md to fix that. 

The code (`sys.path.append('../')`) was actually working on my machine (Mac OS). However, it seems like because other OS can have different path formations, it can break. So, I had a fix for that. The fix has been committed and Zenodo archive is updated. 

`python titanic-all.py` is wrong. I fixed the error in all INSTALL.md. 

AIF360 full installation would not be needed for titanic. But simple install still needed [updated the doc]. 
For simple installation, run `pip install 'aif360[all]'` in the conda environment. 
For full installation, instruction is provided in INSTALL.md and tested on Mac OS. However, if still there is issue for a specific machine environment, follow installation guide from library documentation here (https://github.com/IBM/AIF360).

**Comment by kstolee** [comment]
@rac00n99 We would appreciate your review till Monday morning AoE.

**Comment by rac00n99** [comment]
AVAILABLE: The DOI link is on Zenodo and it works. The folder of the submission shows the description of all the folders contained. 

FUNCTIONAL AND REUSABLE:

Documented: Very well documented, they also provide the description on how to set the environment

Consistent and Complete: The instruction and the file is given to provide all the instruction in order to run the experiment 

Exercisable: All the material for the experiment is included 

> The code (sys.path.append('../')) was actually working on my machine (Mac OS). However, it seems like because other OS can have different path formations, it can break. So, I had a fix for that. The fix has been committed and Zenodo archive is updated.

Maybe as for the problem of paths, I know that it can seem obvious, but you could clarify this in the documentation.

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi Authors,

Thanks for updating the documentation and the code on Zenodo. I do agree on the fact that the documentation appears well written and detailed.
Unfortunately, I still cannot run and replicate the results. The installation of the libraries and the environment goes well, without any errors or warnings, but the code itself fails for imports. 
@kstolee , feel free to make the decision on the label, also based on the feedback from @rac00n99 .

### Recommended Badge: Available

I'm listing here all the steps so you can replicate this for future reference:

```
#Create new docker container
docker pull ubuntu:latest
docker run -it -v  /fse-artifact/260/:/data ubuntu:latest 

#Update packages
apt update
apt-get upgrade
apt install wget
apt install unzip

#Install Anaconda
bash Anaconda3-2020.02-Linux-x86_64.sh

#Create conda environment
conda create --name mlfairness python=3.7
conda activate mlfairness

#Install libs
pip install --ignore-installed --upgrade 'tensorflow >= 1.13.1, < 2'
pip install xgboost imblearn catboost lightgbm

#Download repository
wget https://zenodo.org/record/3902131/files/sumonbis/ML-Fairness-2.1.zip
unzip ML-Fairness-2.1.zip

#Try to run
cd /data/sumonbis-ML-Fairness-209408f/src/models/
./models.sh titanic 1

Started running model 1 for the task titanic
Traceback (most recent call last):
  File "titanic/model1.py", line 7, in <module>
    from packages import *
  File "../utils/packages.py", line 1, in <module>
    from IPython.display import Markdown, display
ModuleNotFoundError: No module named 'IPython'
```

**Comment by sumonbis** [comment]
Thanks for pointing that. I just found that you are running it on Docker and it looks like the issue is with the import path of utility Python files.

[This StackOverflow](https://stackoverflow.com/questions/49631146/how-do-you-add-a-path-to-pythonpath-in-a-dockerfile) post shows that for Docker, PATH has to be added as an environment variable. I will add that to the documentation.

**Comment by gousiosg** [comment]
Applying `available`. 

@RandomlyGeneratedReviewerAccount does the artifact work for you now? 

@rac00n99 and @RandomlyGeneratedReviewerAccount would you recommend any badge other than `available`? 

@all Please make sure you finish your reviews in time; we need to make decisions by Jul 1rst/

**Comment by RandomlyGeneratedReviewerAccount** [comment]
@sumonbis , which custom path should it point to? Please add these steps in the documentation if you want me to test again.

As I said before, I tried my best to replicate and run the tool, but please do feel free to make the decision on the label, also based on the feedback from @rac00n99 .

**Comment by sumonbis** [comment]
Hi @RandomlyGeneratedReviewerAccount,
I have updated the code to fix the import issue. The Zenodo repo and Github source have been updated. Please test it again. Thanks.

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi Authors,

Thanks for the update.
I've tested the most recent code uploaded on Zenodo. The previous import error is solved.

Unfortunately, now the error is due to the failing installation of AIF360.
I tried to install it using the instructions in the documentation (downloading the github repo, etc..), and also using the basic installation you mentioned above (`pip install 'aif360[all]'`).

I'm attaching here the log of the error during the installation, which I run within the conda environment.
[error.txt](https://github.com/researchart/fse20/files/4840046/error.txt)

As a result, now the error is the following:

```
(mlfairness) root@4c00f9cabf8a:/data/sumonbis-ML-Fairness-adf99cf/src/models# ./models.sh titanic 1
Started running model 1 for the task titanic
Traceback (most recent call last):
  File "titanic/model1.py", line 7, in <module>
    from packages import *
  File "../utils/packages.py", line 8, in <module>
    from aif360.datasets import *
ModuleNotFoundError: No module named 'aif360'
```

**Comment by sumonbis** [comment]
Hi @RandomlyGeneratedReviewerAccount,

Could you please try again with `pip install aif360 ` to install AIF360? 

If this still does not work, I think that is because of CVXPY requirement. To install that,

On MacOS, you may first have to install the Xcode Command Line Tools if you
never have previously:

```sh
xcode-select --install
```

On Windows, you may need to download the [Microsoft C++ Build Tools for Visual
Studio 2019](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=BuildTools&rel=16).
See the [CVXPY Install](https://www.cvxpy.org/install/index.html#mac-os-x-windows-and-linux)
page for up-to-date instructions.

Please try again. I think this would work. Thanks.

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi @sumonbis ,

I reported my steps above, and it is clear that I'm testing on linux (ubuntu docker), neither MacOS nor Windows, so I'm not sure why you are reporting those steps.

The installation of cvspy fails. It appears to be a problem for the use PEP 517. 
Here is the log:
[error-cvxpy.txt](https://github.com/researchart/fse20/files/4841426/error-cvxpy.txt)

I Installed aif360 successfully with that command, but when I run the model, I got this:
```
(mlfairness) root@7734dec5a210:/data/sumonbis-ML-Fairness-adf99cf/src/models# ./models.sh titanic 1
Started running model 1 for the task titanic
WARNING:root:No module named 'numba': LFR will be unavailable. To install, run:
pip install 'aif360[LFR]'
Computing fairness of the model.
Computing fairness of the model.
Traceback (most recent call last):
  File "titanic/model1.py", line 206, in <module>
    DIR = DisparateImpactRemover()
  File "/root/anaconda3/envs/mlfairness/lib/python3.7/site-packages/aif360/algorithms/preprocessing/disparate_impact_remover.py", line 29, in __init__
    from BlackBoxAuditing.repairers.GeneralRepairer import Repairer
ModuleNotFoundError: No module named 'BlackBoxAuditing'
```

Thus, I ran the command `pip install 'aif360[LFR]'`, which appears to successfully intsall that lib, but when I run again it fails again (note there is a different warning):

```
(mlfairness) root@7734dec5a210:/data/sumonbis-ML-Fairness-adf99cf/src/models# ./models.sh titanic 1
Started running model 1 for the task titanic
WARNING:root:No module named 'numba.decorators': LFR will be unavailable. To install, run:
pip install 'aif360[LFR]'
Computing fairness of the model.
Computing fairness of the model.
Traceback (most recent call last):
  File "titanic/model1.py", line 206, in <module>
    DIR = DisparateImpactRemover()
  File "/root/anaconda3/envs/mlfairness/lib/python3.7/site-packages/aif360/algorithms/preprocessing/disparate_impact_remover.py", line 29, in __init__
    from BlackBoxAuditing.repairers.GeneralRepairer import Repairer
ModuleNotFoundError: No module named 'BlackBoxAuditing'
```

**Comment by sumonbis** [comment]
> Computing fairness of the model.
> Computing fairness of the model.

Now, the model is running. It has completed first two mitigation algorithms and failing for the third one and that is because of the incomplete installation of AIF360. 

Could you try to install cvxpy again with `conda install -c conda-forge cvxpy ` and then try the complete installation of AIF360 with `pip install 'aif360[all]'`? Thanks for your time.

**Comment by RandomlyGeneratedReviewerAccount** [comment]
Hi @sumonbis ,

That worked. I was able to install the dependency and compute the fairness on several models.

Please, update the documentation with the installation commands, and also make sure to describe the output of the csv content, not only in relationship with the paper.

### Recommended Badge: Available & Reusable

**Comment by sumonbis** [comment]
@RandomlyGeneratedReviewerAccount, 

Great! Thanks. I have updated the documentation and pushed it to GitHub and Zenodo archive.

**Comment by kstolee** [comment]
Thanks for all the work. @rac00n99 are you in agreement on ```reusable```?

**Comment by gousiosg** [comment]
@rac00n99 please let us know today. We will default to  `reusable` except if you argue otherwise.

**Comment by rac00n99** [comment]
`@rac00n99 please let us know today. We will default to reusable except if you argue otherwise.`

Sorry for my delay, I agree with the reusable!

**Comment by kstolee** [comment]
Applying ```reusable```, thanks everyone for your work on this!
